# @package _global_

defaults:
  - override /hydra/sweeper: optuna

hydra:
  mode: "MULTIRUN"
  sweeper:
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
    storage: null
    study_name: convnext_nano_optimization
    n_trials: 10
    n_jobs: 4
    direction: maximize
    sampler:
      _target_: optuna.samplers.TPESampler
      seed: 42
    params:
      model.lr: interval(1e-4, 1e-2)
      model.weight_decay: interval(1e-6, 1e-4)
      model.drop_rate: interval(0.0, 0.3)
      data.batch_size: choice(32, 64, 128)
      trainer.max_epochs: choice(2, 3, 4)

optimized_metric: "val/acc"
