name: Hyperparameter Optimization and Report

on:
  push:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  hyperparameter-optimization-and-report:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - uses: iterative/setup-cml@v2

      - name: Install uv
        uses: astral-sh/setup-uv@v2

      - name: Set up Python 3.12
        run: uv python install 3.12

      - name: Install dependencies
        env:
          UV_EXTRA_INDEX_URL: https://download.pytorch.org/whl/cpu
        run: |
          uv sync 

      - name: Run Hyperparameter Optimization
        run: |
          uv run python src/train.py hparams_search=optuna --multirun

      - name: Generate report
        run: |
          uv run python scripts/generate_hparam_report.py

      - name: Create CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cml comment create hparam_report.md

      - name: Upload plots
        uses: actions/upload-artifact@v3
        with:
          name: hparam-plots
          path: |
            plots/val_loss_plot.png
            plots/val_acc_plot.png
